<?php

session_start(); // start the session

// include some stuff....
include('./db.inc.php');	// database connection
include('./user.php');		// user class definition
include('./my_debug.php');	// my debug functions

// initialize some variables....
$error_messages=array();

// check for logout request
if($_GET['logout']) {
	session_destroy();	// destroy the session
	session_start();	// and start a new session
}

// check for serialized user object in the session
if(isset($_SESSION['suo'])) {
	$user=unserialize($_SESSION['suo']);
} else {
	// new user object
	$user=new user();
}

// ************ validate and handle user input **********//
if(count($_POST)>0) { 								// someone is trying to login or register
	if($_POST['login_name']!='') { 					// someone is trying to login
		myDebug("Login");
		$user->username=$_POST['login_name']; 		// set username
		if(!$user->login()) { 						// attempt a login
			$error_messages[]=$user->last_error;
		}
		else {
			$_SESSION['suo']=serialize($user);		// store the user object in the session
			$redirect = header( "Location: settings.php" ); // Login successful --> redirect to seeting page
			echo $redirect;
		}
	} 
}
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- Generated by Avanquest Technology v:7.1. For information please visit: http://www.avanquestusa.com/ -->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title> VoiSurfing &raquo; Page 1 of 1 </title>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<meta http-equiv="Content-Style-Type" content="text/css;" />
	<link rel="stylesheet" href="voisurfing.css" type="text/css" media="screen,projection,print" />	<!--// Document Style //-->
	<link rel="stylesheet" href="index.css" type="text/css" media="screen,projection,print" />	<!--// Page Style //-->
</head>
<body>
<div id="page">

<!-- login form -->
<form name='login_form' action='index.php' method='post' onsubmit="hashPass();">
	<input type="hidden" name="login_pass_md5" id="login_pass_md5" />
	<!-- load header image including login image -->
	<span id="upperbar"></span>
	<span id="headerwithlogin"></span>
	<input id="login_name" class="smallform" type="text" name="login_name" size="15" value="<?php echo($_POST['login_name']); ?>" />
	<input id="login_password" class="smallform" type="password" name="login_password" size="15" />
	<input id="remember" class="littleform" type="checkbox" name="remember_checkbox"/>
	<!--
	<input id="loginbutton" class="littleform" type="submit" value="Login" action="submit" />
	-->
	<input id="loginbutton" type="image" src="loginbutton.png" alt="Login" action="submit">
	<div id=login_error class="login_error"> 
<?php 
	// output login error messages if there are any
	$error = '';
	foreach($error_messages as $error_message) {
		$error .= $error_message . ' ';
	}
	
	echo $error; 
?> 
	</div>
</form>

<!-- user info, register, logoutout div -->
<div id="usermng" class="usermng">
	Hello:
<?php 
	if($user->logged_in) { // output welcome message
?>
	<?php echo($user->username); ?> , 
	<a href="index.php?logout=true"> Logout</a>
<?php 
	} else { // user not logged in!
?>
	Guest, 
	<a href="register.php"> Register </a>
<?php
}
?>
</div>


<!-- load body image -->
<span id="bodyimage"></span>
<a href="register.php"><span id="joinus"></span></a>


<!-- footter links -->
<div id="main" class="footer">
	<a href="index.php">
	Main</a>
</div>
<div id="overview" class="footer">
	<a href="overview.php">
	Overview</a>
</div>
<div id="register" class="footer">
	<a href="register.php">
	JoinUs</a>
</div>
<div id="login" class="footer">
	<a href="login.php">
	Login</a>
</div>
<div id="settings" class="footer">
	<a href="settings.php">
	Settings</a>
</div>
<div id="contact" class="footer">
	<a href="contact.php">
	Contact Us</a>
</div>


</div>
</body>
</html>
